# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-04 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabuser',
            name='pswd',
            field=models.CharField(default='password', max_length=50),
            preserve_default=False,
        ),
    ]
