# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-07 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20180406_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabfood',
            name='dateuid',
            field=models.CharField(default=1522995815663, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabroom',
            name='dateuid',
            field=models.CharField(default='1522995815663', max_length=15),
            preserve_default=False,
        ),
    ]
