# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20180407_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabadmin',
            name='tel',
            field=models.CharField(default='18788261701', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
