# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_tabadmin_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabspe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=12)),
                ('info', models.TextField()),
                ('imgpath', models.CharField(max_length=100)),
                ('dateuid', models.CharField(max_length=15)),
            ],
        ),
    ]
